### ISSUE TITLE
Method toArray() should respect options from constructor

### ISSUE THREAD

**Issue by mysutka** [atk14/TableRecord#2]
When do_not_read_values is set in constructor, then toArray() method should not return these fields.

**Comment by yarri** [comment]
This is actually not something we want. The option do_not_read_values is used in a different meaning. It gives a TableRecord object hint to not to read some field during the object instantiation, but only read the value when it is needed - i.e. during getValue() or toArray(). It is very usefull for object with large values which are not used frequently (e.g. binary content of a picture). 

Maybe a new option should be created - ignore_values.

**Comment by mysutka** [comment]
Ok, i understand. It is actually documented.
